### ISSUE TITLE
Default case

### ISSUE THREAD

**Issue by IgorNstu** [n00namethe/eltex#10]
https://github.com/n00namethe/eltex/blob/f5a5a7a865bf7ccb60b8511013e6c30a81ca1e42/adbook/adbook.c#L131

Стоит обзавестись дефолтным кейсом в свиче, чтобы отследить сценарий, когда пользователь ввёл номер не_существующей опции и сообщить об этом

**Comment by n00namethe** [comment]
sooqa

**Comment by n00namethe** [comment]
Исправлено
