### ISSUE TITLE
Унификация пробелов около =, ==, и т.п

### ISSUE THREAD

**Issue by kirill-lastochkin-noveo** [n00namethe/eltex#19]
https://github.com/n00namethe/eltex/blob/8afc13d62b85df1b20fa6a2455615cb02cf87b10/dinadbook/adbookd.c#L37
Хороший код стайл а == б, но как автор кода можешь выбирать и а=б. Главное - по всему коду придерживаться выбранного стиля. Ниже по коду операторы с пробелами, предлагаю везде делать также

**Comment by kirill-lastochkin-noveo** [comment]
как я и сказал, я бы выбрал вариант с пробелами, но сам можешь выбирать такой стиль, как хочешь.
только вот тут потерял еще
https://github.com/n00namethe/eltex/blob/0e6929c955b0eb6a719b128e33793255d0733a23/dinadbook/adbookd.c#L75

**Comment by IgorNstu** [comment]
Можно выбрать любой, но при работе с Си, отталкиваясь от:

- кода ядра (linux/Documentation/CodingStyle)
- большинства код-стайлов, включая гугель код стайл
- примеров кода в книге от автора языка
- https://users.ece.cmu.edu/~eno/coding/CCodingStandard.html
- https://www.gnu.org/prep/standards/html_node/Writing-C.html


стоит выбрать путь пробелов(все равно на любом проекте это уже сделают за тебя, и нужно будет переучиваться в итоге)

правило простое:
Бинарные операторы =, +, -, *, /, %, &&, ||, ^, |, &, ==, >, <, >=, <= и др. обрамляются пробелами слева и справа. Между унарным оператором и его операндом пробел не ставится. После запятой всегда ставится пробел.

Читаемость кода , скорее всего, повысится и какие то баги прощу будут обнаружатся аналитически.

e.g.

```
int fun(int a, int b, int c)
{
	int x = 2, y = 0, z = 5;

	x += y - z / (a - b) * (-c) % -b;
	if (x >= a || z == 0)
	{
		is_found = 1;
	}

	printf("Value x = %d / %d", a, b);

	return --x / y++;
}
```
