### ISSUE TITLE
Использование enum

### ISSUE THREAD

**Issue by kirill-lastochkin-noveo** [n00namethe/eltex#28]
https://github.com/n00namethe/eltex/blob/0e6929c955b0eb6a719b128e33793255d0733a23/dinadbook/adbookd.c#L62
Сйчас ты сделал через int j, который пихаешь в свитч. Ок, это работает, но чтобы стороннему человеку понять, что происходит, надо дополнительно просмотреть окружающий код. Понятнее будет
enum Action {
  Add,
  Remove,
  ...
}
...
Action action = Add/Remove/...;
switch (action) 
case Add:
...
case Remove:
...
Тогда можно избавиться от комментов, а по енуму будет сразу видно, какие действия доступны

**Comment by IgorNstu** [comment]
Язык программирования Си
Брайан Керниган, Деннис Ритчи
3-е издание

2.3. Константы
A 8.4. Перечисления

**Comment by IgorNstu** [comment]
Появились перечисления, они в коде говорят сами за себя, комментарии нужно убирать
