### ISSUE TITLE
Попытка добавления в полный массив

### ISSUE THREAD

**Issue by IgorNstu** [n00namethe/eltex#6]
https://github.com/n00namethe/eltex/blob/f5a5a7a865bf7ccb60b8511013e6c30a81ca1e42/adbook/adbook.c#L59

Стоит вывести какое от сообщение о том, что при попытке добавления новой записи оказалось что свободных мест нет. "Sold out"

**Comment by n00namethe** [comment]
совместными усилиями допилено
