### ISSUE TITLE
Вывод всех совпадающих номеров

### ISSUE THREAD

**Issue by IgorNstu** [n00namethe/eltex#7]
https://github.com/n00namethe/eltex/blob/f5a5a7a865bf7ccb60b8511013e6c30a81ca1e42/adbook/adbook.c#L100
Так как проверки на уникальность при добавлении новой записи нет, то можно добаить несколько записей с одним номером, а выведена при поиске будет только одна

**Comment by n00namethe** [comment]
допилено
